version: "3.9" # optional since v1.27.0
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - ./.env
    environment:
      - DB_HOST_DEV=host.docker.internal
  database:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env 