name: learn-github-actions
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: npm install
      - run: npm run test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
          DB_NAME_DEV: ${{ secrets.DB_NAME_DEV }}
          DB_USER_DEV: ${{ secrets.DB_USER_DEV }}
          DB_PASS_DEV: ${{ secrets.DB_PASS_DEV }}
          DB_HOST_DEV: ${{ secrets.DB_HOST_DEV }}
          DB_PORT_DEV: ${{ secrets.DB_PORT_DEV }}
          DB_DIALECT_DEV: ${{ secrets.DB_DIALECT_DEV }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          PGSSLMODE: ${{ secrets.PGSSLMODE }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_EMAIL: ${{ secrets.MAIL_EMAIL }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
  deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.EMAIL }}
          branch: main