name: heroku

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: npm install
#       - run: npm run test
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
          DATABASE_SECRET: ${{ secrets.DATABASE_SECRET }}
          USERNAME_SECRET: ${{ secrets.USERNAME_SECRET }}
          PASSWORD_SECRET: ${{ secrets.PASSWORD_SECRET }}
          HOST_SECRET: ${{ secrets.HOST_SECRET }}
          PORT_SECRET: ${{ secrets.PORT_SECRET }}
          DIALECT_SECRET: ${{ secrets.DIALECT_SECRET }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          PGSSLMODE: ${{ secrets.PGSSLMODE }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          CUSTOMER_ID: ${{ secrets.CUSTOMER_ID }}
          ITEM_ID: ${{ secrets.ITEM_ID }}
          ORDER_ID: ${{ secrets.ORDER_ID }}
  deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: master


# name: Deploy to HeroKu

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: akhileshns/heroku-deploy@v3.12.12
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
#           heroku_email: ${{secrets.HEROKU_EMAIL}}

